### ISSUE TITLE
Vulnerable to desktop enumeration attacks?

### ISSUE THREAD

**Issue by fritzophrenic** [AlphaDelta/Secure-Desktop#9]
I stumbled on your project while looking into the security of the "Secure Desktop" feature of some password managers (notably, KeePass and 1Password), and from briefly reading the project description, it looks like it _may_ work in the same way. So, I apologize if this doesn't apply here.

Apparently just creating a new desktop for a program isn't enough to guard against keyloggers. A trivial attack is to enumerate the desktops and create a new process on each of them, as demonstrated for both [KeePass](https://www.trustwave.com/Resources/Security-Advisories/Advisories/TWSL2014-011/?fid=3730) and [1Password](https://www.trustwave.com/Resources/Security-Advisories/Advisories/TWSL2014-012/?fid=3729).

[1Password came up with a workaround](https://blog.agilebits.com/2014/08/21/watch-what-you-type-1passwords-defenses-against-keystroke-loggers/), to detect when unexpected processes are running in the same desktop, it may be possible to do something similar here if your application is actually vulnerable.

**Comment by AlphaDelta** [comment]
The desktop is initialized without the `DESKTOP_ENUMERATE` access flag (see [here](https://github.com/AlphaDelta/Secure-Desktop/blob/master/SecureDesktop/WinAPI.cs#L60-L64)) which supposedly prevents the desktop from being revealed by the Windows API, although I've never actually tested it. I also use the ISAAC CSPRNG with seeds built from some random information on startup to create the desktop name so that malicious programs cannot switch to the desktop by name.

It is definitely possible to do a process check every second or so to prevent malicious programs from popping up inside the desktop, however that would break the functionality of many programs that rely on multiple processes (maybe have an Allow/Deny popup when a new process is found?).

Despite all that memory injection is still a possibility. It might help to run Secure Desktop as an administrator, however I would _greatly_ advise against that because of the possibility of running a malicious program _in_ Secure Desktop, in which case it would have administrative privileges.
